sourcekitten_sourcefile: awssdkswift.json
author: Yuki Takei, Joe Smith, Jonathan McAllister, Adam Fowler
author_url: https://github.com/swift-aws
github_url: https://github.com/swift-aws/aws-sdk-swift
copyright: '© Copyright (c) 2019 Yuki Takei(noppoMan), Joe Smith(Yasumoto), Jonathan McAllister(jonnymacs), Adam Fowler (adam-fowler)'
readme: README.md

custom_categories:

  - name: ACM
    children:
      - ACM
      - ACMErrorType

  - name: APIGateway
    children:
      - APIGateway
      - APIGatewayErrorType

  - name: ACMPCA
    children:
      - ACMPCA
      - ACMPCAErrorType

  - name: AWSBackup
    children:
      - AWSBackup
      - AWSBackupErrorType

  - name: AWSDirectoryService
    children:
      - AWSDirectoryService
      - AWSDirectoryServiceErrorType

  - name: AlexaForBusiness
    children:
      - AlexaForBusiness
      - AlexaForBusinessErrorType

  - name: Amplify
    children:
      - Amplify
      - AmplifyErrorType

  - name: ApiGatewayManagementApi
    children:
      - ApiGatewayManagementApi
      - ApiGatewayManagementApiErrorType

  - name: ApiGatewayV2
    children:
      - ApiGatewayV2
      - ApiGatewayV2ErrorType

  - name: AppMesh
    children:
      - AppMesh
      - AppMeshErrorType

  - name: AppStream
    children:
      - AppStream
      - AppStreamErrorType

  - name: ApplicationAutoScaling
    children:
      - ApplicationAutoScaling
      - ApplicationAutoScalingErrorType

  - name: AppSync
    children:
      - AppSync
      - AppSyncErrorType

  - name: ApplicationDiscoveryService
    children:
      - ApplicationDiscoveryService
      - ApplicationDiscoveryServiceErrorType

  - name: ApplicationInsights
    children:
      - ApplicationInsights
      - ApplicationInsightsErrorType

  - name: Athena
    children:
      - Athena
      - AthenaErrorType

  - name: AutoScaling
    children:
      - AutoScaling
      - AutoScalingErrorType

  - name: AutoScalingPlans
    children:
      - AutoScalingPlans
      - AutoScalingPlansErrorType

  - name: Batch
    children:
      - Batch
      - BatchErrorType

  - name: Budgets
    children:
      - Budgets
      - BudgetsErrorType

  - name: Chime
    children:
      - Chime
      - ChimeErrorType

  - name: CloudDirectory
    children:
      - CloudDirectory
      - CloudDirectoryErrorType

  - name: Cloud9
    children:
      - Cloud9
      - Cloud9ErrorType

  - name: CloudFormation
    children:
      - CloudFormation
      - CloudFormationErrorType

  - name: CloudFront
    children:
      - CloudFront
      - CloudFrontErrorType

  - name: CloudHSM
    children:
      - CloudHSM
      - CloudHSMErrorType

  - name: CloudHSMV2
    children:
      - CloudHSMV2
      - CloudHSMV2ErrorType

  - name: CloudSearchDomain
    children:
      - CloudSearchDomain
      - CloudSearchDomainErrorType

  - name: CloudSearch
    children:
      - CloudSearch
      - CloudSearchErrorType

  - name: CloudTrail
    children:
      - CloudTrail
      - CloudTrailErrorType

  - name: CloudWatch
    children:
      - CloudWatch
      - CloudWatchErrorType

  - name: CloudWatchEvents
    children:
      - CloudWatchEvents
      - CloudWatchEventsErrorType

  - name: CloudWatchLogs
    children:
      - CloudWatchLogs
      - CloudWatchLogsErrorType

  - name: CodeBuild
    children:
      - CodeBuild
      - CodeBuildErrorType

  - name: CodeCommit
    children:
      - CodeCommit
      - CodeCommitErrorType

  - name: CodeDeploy
    children:
      - CodeDeploy
      - CodeDeployErrorType

  - name: CodePipeline
    children:
      - CodePipeline
      - CodePipelineErrorType

  - name: CodeStarNotifications
    children:
      - CodeStarNotifications
      - CodeStarNotificationsErrorType

  - name: CodeStar
    children:
      - CodeStar
      - CodeStarErrorType

  - name: CognitoIdentity
    children:
      - CognitoIdentity
      - CognitoIdentityErrorType

  - name: CognitoIdentityProvider
    children:
      - CognitoIdentityProvider
      - CognitoIdentityProviderErrorType

  - name: CognitoSync
    children:
      - CognitoSync
      - CognitoSyncErrorType

  - name: Comprehend
    children:
      - Comprehend
      - ComprehendErrorType

  - name: ComprehendMedical
    children:
      - ComprehendMedical
      - ComprehendMedicalErrorType

  - name: ConfigService
    children:
      - ConfigService
      - ConfigServiceErrorType

  - name: Connect
    children:
      - Connect
      - ConnectErrorType

  - name: CostExplorer
    children:
      - CostExplorer
      - CostExplorerErrorType

  - name: CostandUsageReportService
    children:
      - CostandUsageReportService
      - CostandUsageReportServiceErrorType

  - name: DAX
    children:
      - DAX
      - DAXErrorType

  - name: DLM
    children:
      - DLM
      - DLMErrorType

  - name: DataPipeline
    children:
      - DataPipeline
      - DataPipelineErrorType

  - name: DataSync
    children:
      - DataSync
      - DataSyncErrorType

  - name: DatabaseMigrationService
    children:
      - DatabaseMigrationService
      - DatabaseMigrationServiceErrorType

  - name: DeviceFarm
    children:
      - DeviceFarm
      - DeviceFarmErrorType

  - name: DirectConnect
    children:
      - DirectConnect
      - DirectConnectErrorType

  - name: DocDB
    children:
      - DocDB
      - DocDBErrorType

  - name: DynamoDB
    children:
      - DynamoDB
      - DynamoDBErrorType

  - name: DynamoDBStreams
    children:
      - DynamoDBStreams
      - DynamoDBStreamsErrorType

  - name: EC2
    children:
      - EC2
      - EC2ErrorType

  - name: EC2InstanceConnect
    children:
      - EC2InstanceConnect
      - EC2InstanceConnectErrorType

  - name: ECR
    children:
      - ECR
      - ECRErrorType

  - name: ECS
    children:
      - ECS
      - ECSErrorType

  - name: EFS
    children:
      - EFS
      - EFSErrorType

  - name: EKS
    children:
      - EKS
      - EKSErrorType

  - name: ELB
    children:
      - ELB
      - ELBErrorType

  - name: ELBV2
    children:
      - ELBV2
      - ELBV2ErrorType

  - name: EMR
    children:
      - EMR
      - EMRErrorType

  - name: ElastiCache
    children:
      - ElastiCache
      - ElastiCacheErrorType

  - name: ElasticBeanstalk
    children:
      - ElasticBeanstalk
      - ElasticBeanstalkErrorType

  - name: ElasticTranscoder
    children:
      - ElasticTranscoder
      - ElasticTranscoderErrorType

  - name: ElasticsearchService
    children:
      - ElasticsearchService
      - ElasticsearchServiceErrorType

  - name: EventBridge
    children:
      - EventBridge
      - EventBridgeErrorType

  - name: FMS
    children:
      - FMS
      - FMSErrorType

  - name: FSx
    children:
      - FSx
      - FSxErrorType

  - name: Firehose
    children:
      - Firehose
      - FirehoseErrorType

  - name: ForecastQueryService
    children:
      - ForecastQueryService
      - ForecastQueryServiceErrorType

  - name: ForecastService
    children:
      - ForecastService
      - ForecastServiceErrorType

  - name: GameLift
    children:
      - GameLift
      - GameLiftErrorType

  - name: Glacier
    children:
      - Glacier
      - GlacierErrorType

  - name: GlobalAccelerator
    children:
      - GlobalAccelerator
      - GlobalAcceleratorErrorType

  - name: Glue
    children:
      - Glue
      - GlueErrorType

  - name: Greengrass
    children:
      - Greengrass
      - GreengrassErrorType

  - name: GuardDuty
    children:
      - GuardDuty
      - GuardDutyErrorType

  - name: GroundStation
    children:
      - GroundStation
      - GroundStationErrorType

  - name: Health
    children:
      - Health
      - HealthErrorType

  - name: IAM
    children:
      - IAM
      - IAMErrorType

  - name: ImportExport
    children:
      - ImportExport
      - ImportExportErrorType

  - name: Inspector
    children:
      - Inspector
      - InspectorErrorType

  - name: IoT
    children:
      - IoT
      - IoTErrorType

  - name: IoT1ClickDevicesService
    children:
      - IoT1ClickDevicesService
      - IoT1ClickDevicesServiceErrorType

  - name: IoT1ClickProjects
    children:
      - IoT1ClickProjects
      - IoT1ClickProjectsErrorType

  - name: IoTAnalytics
    children:
      - IoTAnalytics
      - IoTAnalyticsErrorType

  - name: IoTDataPlane
    children:
      - IoTDataPlane
      - IoTDataPlaneErrorType

  - name: IoTEvents
    children:
      - IoTEvents
      - IoTEventsErrorType

  - name: IoTEventsData
    children:
      - IoTEventsData
      - IoTEventsDataErrorType

  - name: IoTJobsDataPlane
    children:
      - IoTJobsDataPlane
      - IoTJobsDataPlaneErrorType

  - name: IoTThingsGraph
    children:
      - IoTThingsGraph
      - IoTThingsGraphErrorType

  - name: KMS
    children:
      - KMS
      - KMSErrorType

  - name: Kafka
    children:
      - Kafka
      - KafkaErrorType

  - name: Kinesis
    children:
      - Kinesis
      - KinesisErrorType

  - name: KinesisAnalytics
    children:
      - KinesisAnalytics
      - KinesisAnalyticsErrorType

  - name: KinesisAnalyticsV2
    children:
      - KinesisAnalyticsV2
      - KinesisAnalyticsV2ErrorType

  - name: KinesisVideo
    children:
      - KinesisVideo
      - KinesisVideoErrorType

  - name: KinesisVideoArchivedMedia
    children:
      - KinesisVideoArchivedMedia
      - KinesisVideoArchivedMediaErrorType

  - name: KinesisVideoMedia
    children:
      - KinesisVideoMedia
      - KinesisVideoMediaErrorType

  - name: LakeFormation
    children:
      - LakeFormation
      - LakeFormationErrorType

  - name: Lambda
    children:
      - Lambda
      - LambdaErrorType

  - name: LexModelBuildingService
    children:
      - LexModelBuildingService
      - LexModelBuildingServiceErrorType

  - name: LexRuntimeService
    children:
      - LexRuntimeService
      - LexRuntimeServiceErrorType

  - name: LicenseManager
    children:
      - LicenseManager
      - LicenseManagerErrorType

  - name: Lightsail
    children:
      - Lightsail
      - LightsailErrorType

  - name: MQ
    children:
      - MQ
      - MQErrorType

  - name: MTurk
    children:
      - MTurk
      - MTurkErrorType

  - name: MachineLearning
    children:
      - MachineLearning
      - MachineLearningErrorType

  - name: Macie
    children:
      - Macie
      - MacieErrorType

  - name: ManagedBlockchain
    children:
      - ManagedBlockchain
      - ManagedBlockchainErrorType

  - name: MarketplaceCommerceAnalytics
    children:
      - MarketplaceCommerceAnalytics
      - MarketplaceCommerceAnalyticsErrorType

  - name: MarketplaceEntitlementService
    children:
      - MarketplaceEntitlementService
      - MarketplaceEntitlementServiceErrorType

  - name: MarketplaceMetering
    children:
      - MarketplaceMetering
      - MarketplaceMeteringErrorType

  - name: MediaConnect
    children:
      - MediaConnect
      - MediaConnectErrorType

  - name: MediaConvert
    children:
      - MediaConvert
      - MediaConvertErrorType

  - name: MediaLive
    children:
      - MediaLive
      - MediaLiveErrorType

  - name: MediaPackage
    children:
      - MediaPackage
      - MediaPackageErrorType

  - name: MediaPackageVod
    children:
      - MediaPackageVod
      - MediaPackageVodErrorType

  - name: MediaStore
    children:
      - MediaStore
      - MediaStoreErrorType

  - name: MediaStoreData
    children:
      - MediaStoreData
      - MediaStoreDataErrorType

  - name: MediaTailor
    children:
      - MediaTailor
      - MediaTailorErrorType

  - name: MigrationHub
    children:
      - MigrationHub
      - MigrationHubErrorType

  - name: Mobile
    children:
      - Mobile
      - MobileErrorType

  - name: MobileAnalytics
    children:
      - MobileAnalytics
      - MobileAnalyticsErrorType

  - name: Neptune
    children:
      - Neptune
      - NeptuneErrorType

  - name: OpsWorks
    children:
      - OpsWorks
      - OpsWorksErrorType

  - name: OpsWorksCM
    children:
      - OpsWorksCM
      - OpsWorksCMErrorType

  - name: Organizations
    children:
      - Organizations
      - OrganizationsErrorType

  - name: PI
    children:
      - PI
      - PIErrorType

  - name: Personalize
    children:
      - Personalize
      - PersonalizeErrorType

  - name: PersonalizeEvents
    children:
      - PersonalizeEvents
      - PersonalizeEventsErrorType

  - name: PersonalizeRuntime
    children:
      - PersonalizeRuntime
      - PersonalizeRuntimeErrorType

  - name: Pinpoint
    children:
      - Pinpoint
      - PinpointErrorType

  - name: PinpointEmail
    children:
      - PinpointEmail
      - PinpointEmailErrorType

  - name: PinpointSMSVoice
    children:
      - PinpointSMSVoice
      - PinpointSMSVoiceErrorType

  - name: Polly
    children:
      - Polly
      - PollyErrorType

  - name: Pricing
    children:
      - Pricing
      - PricingErrorType

  - name: QLDB
    children:
      - QLDB
      - QLDBErrorType

  - name: QLDBSession
    children:
      - QLDBSession
      - QLDBSessionErrorType

  - name: QuickSight
    children:
      - QuickSight
      - QuickSightErrorType

  - name: RAM
    children:
      - RAM
      - RAMErrorType

  - name: RDS
    children:
      - RDS
      - RDSErrorType

  - name: RDSDataService
    children:
      - RDSDataService
      - RDSDataServiceErrorType

  - name: Redshift
    children:
      - Redshift
      - RedshiftErrorType

  - name: Rekognition
    children:
      - Rekognition
      - RekognitionErrorType

  - name: ResourceGroups
    children:
      - ResourceGroups
      - ResourceGroupsErrorType

  - name: ResourceGroupsTaggingAPI
    children:
      - ResourceGroupsTaggingAPI
      - ResourceGroupsTaggingAPIErrorType

  - name: RoboMaker
    children:
      - RoboMaker
      - RoboMakerErrorType

  - name: Route53
    children:
      - Route53
      - Route53ErrorType

  - name: Route53Domains
    children:
      - Route53Domains
      - Route53DomainsErrorType

  - name: Route53Resolver
    children:
      - Route53Resolver
      - Route53ResolverErrorType

  - name: S3+multipart
    children:
      - S3+multipart
      - S3+multipartErrorType

  - name: S3
    children:
      - S3
      - S3ErrorType

  - name: S3Control
    children:
      - S3Control
      - S3ControlErrorType

  - name: SES
    children:
      - SES
      - SESErrorType

  - name: SFN
    children:
      - SFN
      - SFNErrorType

  - name: SMS
    children:
      - SMS
      - SMSErrorType

  - name: SNS
    children:
      - SNS
      - SNSErrorType

  - name: SQS
    children:
      - SQS
      - SQSErrorType

  - name: SSM
    children:
      - SSM
      - SSMErrorType

  - name: SSO
    children:
      - SSO
      - SSOErrorType

  - name: SSOOIDC
    children:
      - SSOOIDC
      - SSOOIDCErrorType

  - name: STS
    children:
      - STS
      - STSErrorType

  - name: SWF
    children:
      - SWF
      - SWFErrorType

  - name: SageMaker
    children:
      - SageMaker
      - SageMakerErrorType

  - name: SageMakerRuntime
    children:
      - SageMakerRuntime
      - SageMakerRuntimeErrorType

  - name: SavingsPlans
    children:
      - SavingsPlans
      - SavingsPlansErrorType

  - name: SecretsManager
    children:
      - SecretsManager
      - SecretsManagerErrorType

  - name: SecurityHub
    children:
      - SecurityHub
      - SecurityHubErrorType

  - name: ServerlessApplicationRepository
    children:
      - ServerlessApplicationRepository
      - ServerlessApplicationRepositoryErrorType

  - name: ServiceCatalog
    children:
      - ServiceCatalog
      - ServiceCatalogErrorType

  - name: ServiceDiscovery
    children:
      - ServiceDiscovery
      - ServiceDiscoveryErrorType

  - name: ServiceQuotas
    children:
      - ServiceQuotas
      - ServiceQuotasErrorType

  - name: Shield
    children:
      - Shield
      - ShieldErrorType

  - name: Signer
    children:
      - Signer
      - SignerErrorType

  - name: SimpleDB
    children:
      - SimpleDB
      - SimpleDBErrorType

  - name: Snowball
    children:
      - Snowball
      - SnowballErrorType

  - name: StorageGateway
    children:
      - StorageGateway
      - StorageGatewayErrorType

  - name: Support
    children:
      - Support
      - SupportErrorType

  - name: Textract
    children:
      - Textract
      - TextractErrorType

  - name: TranscribeService
    children:
      - TranscribeService
      - TranscribeServiceErrorType

  - name: Transfer
    children:
      - Transfer
      - TransferErrorType

  - name: Translate
    children:
      - Translate
      - TranslateErrorType

  - name: WAF
    children:
      - WAF
      - WAFErrorType

  - name: WAFRegional
    children:
      - WAFRegional
      - WAFRegionalErrorType

  - name: WorkDocs
    children:
      - WorkDocs
      - WorkDocsErrorType

  - name: WorkLink
    children:
      - WorkLink
      - WorkLinkErrorType

  - name: WorkMail
    children:
      - WorkMail
      - WorkMailErrorType

  - name: WorkMailMessageFlow
    children:
      - WorkMailMessageFlow
      - WorkMailMessageFlowErrorType

  - name: WorkSpaces
    children:
      - WorkSpaces
      - WorkSpacesErrorType

  - name: XRay
    children:
      - XRay
      - XRayErrorType

